version: '3.9'

services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=animal_tracking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  # Сервис для разворачивания контейнера с приложением
  webapi:
    image: animal-tracking:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/animal_tracking
      - spring.datasource.username=postgres
      - spring.datasource.password=DznStilton1.
      - spring.jpa.hibernate.ddl-auto=create-drop
      - server.port=8080


  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080
      STAGE: 2
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа

